---



- name: Install txpower init service for wireless interface (mitigating driver init problem)
  hosts: all
  become: yes

  tasks:
    - name: Check thats Wi-Fi card PCI ID exists
      shell: lspci -nn | grep -i '14e4:43ba'
      register: wifi_card_check
      ignore_errors: yes

    - name: Hardware verified
      fail:
        msg: "Required Wi-Fi card with PCI ID 14e4:43ba is not present."
      when: wifi_card_check.rc != 0

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install firmware-b43legacy-installer package
      apt:
        name: firmware-b43legacy-installer
        state: present

    - name: Create systemd service file for setting txpower
      copy:
        dest: /etc/systemd/system/wifi-txpower-init.service
        content: |
          [Unit]
          Description=Set TX Power for Wireless Interface once at init
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/sbin/iwconfig wlp3s0 txpower 10dBm
          ExecStartPost=bash -c 'sleep 1; ifconfig wlp3s0 down; sleep 1; ifconfig wlp3s0 up'
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target
      when: wifi_card_check.rc == 0

    - name: Reload systemd manager configuration
      command: systemctl daemon-reload
      when: wifi_card_check.rc == 0

    - name: Enable the wifi-txpower-init service
      systemd:
        name: wifi-txpower-init
        enabled: yes
        state: started
      when: wifi_card_check.rc != 0

    - name: Restart Wi-Fi service
      service:
        name: NetworkManager
        state: restarted
      when: wifi_card_check.rc == 0